services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://Horilla:Horilla@145.223.22.51:3232/Horilla"
    command: sh ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - ./media:/app/media
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
