services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://Horilla:Horilla@145.223.22.51:3232/Horilla"
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8088,http://127.0.0.1:8088"
      DEBUG: "False"
      SECURE_SSL_REDIRECT: "0"
      SESSION_COOKIE_SECURE: "0"
      CSRF_COOKIE_SECURE: "0"
    command: sh ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - ./media:/app/media
    # networks:
    #   - dokploy-network

# networks:
  # dokploy-network:
    # external: true